music/urls.py
from django.conf.urls import url
from . import views



app_name = 'music'
# #old urls
urlpatterns = [
				url(r'^$',views.index, name = 'index'),
				

				## /music/712/
				url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
				## /music/712/68
				### first is music url ( the url registered in urls py)
				### second is element passed after the music ( the second is anything basically need not be certainly the album_id )
				### third is when the third element is passed /music/712/68 (third element)
				url(r'^(?P<album_id>[0-9]+)/(?P<sec_al>[0-9]+)/$', views.more_depth, name= 'more'),

				### to favorite it and return the url to same page
				## /music/<album id>/ favorites

				url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
				


]

webdev/webdev/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url 
from audio.views import *
from audio import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', views.homepage),
    url(r'^intro/', views.temp_l),
    url(r'^search/$', views.disp_results),
    url(r'^store/$', views.store_results),
   
   # url(r'^disp_speech/$', views.sample_voice),
   ## to get a syndrome from a user and put it in the database
   url(r'^form/$', views.form_res),
   url(r'^show_more/$',views.get_form_res),
   url(r'^store_syndrome/$',views.store_data),
### rec speech urls
   url(r'^speak/$', views.sample_voice),
   url(r'^show_speech/$', views.display_speech),
   url(r'^speech_save/$', views.save_speech),
   url(r'^doctor_dash/$', views.doctors_view),
   url(r'^show_pat_data/$',views.pat_data),


]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

music/models.py
from django.db import models

# Create your models here.


class Album(models.Model):
	artist = models.CharField(max_length = 250)
	album_name = models.CharField(max_length = 250)
	genre = models.CharField(max_length = 250)

	def __str__(self):
		return self.artist + '' + self.album_name


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete= models.CASCADE)
	song_name = models.CharField(max_length = 250)
	is_favorite = models.BooleanField(default= False)
	
	def __str__(self):
		return self.song_name

music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from music.models import Album , Song
from django.template import loader

### views with templates on

def index(request):
	all_albums = Album.objects.all()
	template = loader.get_template('music/index.html')
	## information that your template needs
	context  = {'all_albums' : all_albums}
	#return HttpResponse(template.render(context, request))
	return render(request, 'music/index.html', context)

## old details view
# def detail(request,album_id):
# 	text = "<h1> Details for Album id is :" + str(album_id) + "</h1>"
# 	return HttpResponse(text)


### use get_object_or_404 to remove try and except syntax
def detail(request, album_id):
	try:
		album = Album.objects.get(pk=album_id)
		template = loader.get_template('music/details.html')
		context = {
		'album': album,
		}
	except Album.DoesNotExist:
		raise Http404(" Album DoesNotExist ")
	return render(request, 'music/details.html', {'album' : album})
	#return HttpResponse(template.render(context, request))

def favorite(request, album_id):
	album  = get_object_or_404(Album, pk=album_id)
	try: 
		## get the value of the song selected
		selected_song = album.song_set.get(pk = request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'music/details.html', 
			{
			"album": album,
			"error_message": "You did not select anything"})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return render(request, 'music/details.html', {'album' : album })



def more_depth(request, album_id, sec_al):
	return HttpResponse("<h2> Details further:" + str(album_id) +"sec_al" + str(sec_al) + "</h2>")

### views




# from django.views import generic
# from music.models import Album
# ## list of all albums
# class IndexView(generic.ListView):
# 	template_name = 'music/index.html'
# 	context_object_name = 'all_albums'

# 	def get_queryset(self):
# 		return Album.objects.all()

# class DetailView(generic.DetailView):
# 	model = Album
# 	template_name = 'music/details.html'

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Viberr</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> 
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"> 

</head>
<body>


<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header" >
			<!-- if the device doesn't have the room to appear -->
			<button type="button" class="navbar-toggle" data-toggle ="collapse" data-target = "#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>	
			<a class="navbar-brand" href="{% url 'music:index' %}">NEWRAZ</a>
		</div>
	

<!-- start adding items -->
	<div class= "collapse navbar-collapse">
		<ul class= "nav navbar-nav">
			<li class="active">
				<a href="{% url 'music:index' %}">
					<span class= "glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
				</a>
			</li>
			<li class="active">
				<a href="{% url 'music:index' %}">
					<span class= "glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
				</a>
			</li>
		</ul>
	<form class="navbar-form navbar-left" role="search" method = "get" action ="#">
		<div class= "form-group">
			<input type = "text" class= "form-control" name= "q" value = "">
		</div>
		<button type="submit" class= "btn btn-default">Search</button>
	</form>
	<!-- copied and pasted the above code   ## the below code is changed to be placed right-->
		<ul class= "nav navbar-nav navbar-right"> 
			<li class="">
				<a href="#">
					<span class= "glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add_Songs
				</a>
			</li>
			<li class="active">
				<a href="#">
					<span class= "glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
				</a>
			</li>
		</ul>


	</div>




</div>
</nav>

<div class="first_sq" id="square_fs"></div>
{% block body %}

{% endblock %}
</body>
</html>

music/templates/music/details.html
<!-- 
{{ album.artist }}
<ul>
{% for song in album.song_set.all %}

<li>{{ song }}</li>
{% endfor %}
</ul>
 -->

<!--load a css file in django 
{% load staticfiles %}
<link rel= "stylesheet" type = "text/css" href= "{% static 'music/style.css' %}" />
## use google fonts
 -->



{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}


<form action="{% url 'music:favorite' album.id %}" method="post">
	{% csrf_token %}
	{{ album.artist }}<br><br>
	{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
		<label for ="song{{ forloop.counter }}">
			{{ song.song_name }}
			{% if song.is_favorite %}
			<img src="file:///C:/Users/adity/Desktop/python_dev/macro-gold-christmas-star-isolated-260nw-741321604.webp">
			{% endif %}
		</label><br>
	{% endfor %}<br><br>
	<input type="submit" name="Favorite">

</form>

music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}
{% if all_albums %}
	<ul>
		<h3>Here are all my Albums: </h3>
		 {% for album in all_albums %} 
		 <li><a href="/music/{{ album.id }}/"> {{ album.album_name }} </a></li>  
		<!-- name space your url if we have multiple apps in the website -->
		{% endfor %}
	</ul>

	{% else %}
		
		<h3> You don't have anything  !! </h3>

	{% endif %}

{% endblock %}